module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/Inhb4ts1A7zAYnQvjW6Ekv',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://cdn.phototourl.com/free/2026-06-30-6f0acaed-3fbd-40fc-b215-31440c3310e8.jpg', //ඒක හරි 
    NEWSLETTER_JID: '120363424546838736@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'CHATHUWA MD BOT',
    OWNER_NAME: 'CHATHUWA MD BOT',
    OWNER_NUMBER: '9474741336839',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> CHATHUWA X MD MINI BOT',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb6zdUyFsn0cyFknXz2t',
};
